apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=realmaxwebapp/my_backend
    argocd-image-updater.argoproj.io/backend.helm.image-name: backend.image.name
    argocd-image-updater.argoproj.io/backend.helm.image-tag: backend.image.tag
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-repository: https://github.com/phucnguyen25392/argo-api
    argocd-image-updater.argoproj.io/git-branch: master
  name: my-backend
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: api
  project: default
  source:
    chart: realchart
    repoURL: https://phucnguyen25392.github.io/devops-charts
    targetRevision: 0.1.3
    helm:
      releaseName: my-backend
      values: |
        name: my-backend
        namespace: api
        serviceAccount:
          # Specifies whether a ServiceAccount should be created
          create: false
          # The name of the ServiceAccount to use.
          # If not set and create is true, a name is generated using the fullname template
          name: ""
        image:
          repository: realmaxwebapp/my_backend
          tag: 1.0.6
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 20
        service:
          port: "8080"
          targetPort: "8080"
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 1024Mi
        priorityClassName: medium-priority
