backend:
  name: my-backend
  namespace: api
  serviceAccount:
    create: false
    name: ""
  image:
    repository: realmaxwebapp/my_backend
    tag: 1.0.6
  livenessProbe:
    httpGet:
      path: /health
      port: http
      scheme: HTTP
    initialDelaySeconds: 20
  readinessProbe:
    httpGet:
      path: /health
      port: http
      scheme: HTTP
    initialDelaySeconds: 20
  service:
    port: "8080"
    targetPort: "8080"
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  priorityClassName: medium-priority
image:
  tag: 1.0.7
  repository: realmaxwebapp/my_backend
